### ISSUE TITLE
Ako moze?

### ISSUE THREAD

**Issue by cira49152** [cira49152/cira49152.github.io#5]
@Ogy75 , hajde ako mozes da postavis nesto u meniju za povratak na home page.
Par puta se zalecem pa onda idem na logo...?

**Comment by Ogy75** [comment]
Naravno, stavicu u meniju i home page link

Ognjen Djokic
Paje Jovanovica 35
11050 Beograd, Srbija
+381 63 296348
ognjen.djokic@gmail.com
